Repository SportsEcho/EchoProject-FE, pull requests merged in 2024-01, with the labels that each got.

#3 Feature/login
  src/App.js
  src/assets/styles/login.css
  src/components/Header/Header.js
  src/components/Login.js
Labels: feature

#29 fix : frontend CD workflow와 signup.js 환경변수 이름이 일치하지 않는 문제 (#28)
  src/components/Login.js
  src/components/Signup.js
Labels: wontfix

#46 게임 실시간 채팅기능을 위한 GameChat 컴포넌트 추가
  package-lock.json
  package.json
  src/App.js
  src/assets/styles/GameChat.css
  src/components/GameChat/GameChat.js
  src/components/Navigation/Navigation.js
Labels: feature

#54 게임별 실시간 채팅 기능 구현
  src/App.js
  src/assets/styles/GameChat.css
  src/components/GameChat/GameChat.js
  src/components/GameDetails/FootballGameDetails.js
  src/components/Navigation/Navigation.js
Labels: feature

#57 GameDetails 및 GameChat 레이아웃 변경
  src/assets/styles/GameDetails.css
  src/components/GameChat/GameChat.js
  src/components/GameDetails/FootballGameDetails.js
Labels: enhancement, feature

#60 로그아웃시 발생하는 버그 해결
  src/components/Header/Header.js
Labels: bug

#70 Feature/login
  src/App.js
  src/api/gameApi.js
  src/components/AuthContext.js
  src/components/GameSchedule/BaseballSchedule.js
  src/components/GameSchedule/BasketballSchedule.js
  src/components/GameSchedule/FootballSchedule.js
  src/components/Login.js
  src/components/MainPage.js
  src/components/Navigation/Navigation.js
Labels: feature

#90 Feature/product
  src/components/Cart/CartPage.js
  src/components/GameDetails/BaseballGameDetails.js
  src/components/GameDetails/BasketballGameDetails.js
  src/components/Hotdeal/HotdealDetail.js
  src/components/Hotdeal/HotdealList.js
Labels: bug, feature

#101 Feature/product
  src/App.js
  src/components/Cart/CartPage.js
  src/components/Purchase/OrderPage.js
Labels: feature

#102 fix : HotdealDetail.js
  src/components/Hotdeal/HotdealDetail.js
  src/components/OAuth/KakaoRedirect.js
  src/components/OAuth/NaverRedirect.js
Labels: bug

#110 fix : 무한 스크롤 구현
  src/components/Product/ProductPage.js
Labels: feature

#114 Feature/product
  src/assets/styles/ProductPage.css
  src/components/Cart/CartPage.js
  src/components/Product/ProductDetailPage.js
Labels: bug

#155 회원가입시 멤버 이름 한국어 허용 및 비밀번호 확인 기능 추가
  src/components/Signup.js
Labels: enhancement

#170 fix:(Hotdeal) : 핫딜 구매시 id값을 인식하지 못하는 현상 수정
  src/App.js
Labels: bug
